server:
  port: 8084

spring:
  application:
    name: make-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rbtestdb
    username: postgres
    password: "123"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

jwt:
  secret: 'n4uB0oP1mQ6sT8yZ0xR3vL7eF2aD5jK9sU8iE4wQ1zC3bN6rT8vY0pL7kJ2dS9aF'

logging:
  level:
    org.springframework.security: INFO
