spring.application.name=make-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/rbtestdb
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=n4uB0oP1mQ6sT8yZ0xR3vL7eF2aD5jK9sU8iE4wQ1zC3bN6rT8vY0pL7kJ2dS9aF
jwt.expiration=3600000

yandex.maps.api-key=${YANDEX_MAPS_API_KEY:fb560341-ba13-42eb-9e2f-fad6f7701d75}

logging.level.org.springframework.web=INFO
