spring.application.name=export-service
server.port=8086

services.make-service=${SERVICES_MAKE_SERVICE:http://localhost:8084}
yandex.maps.api-key=${YANDEX_MAPS_API_KEY:}

logging.level.org.springframework.web=INFO
