services:
  gateway:
    ports:
      - "80:80"
      - "443:443"
      - "8080:80"
    volumes:
      - ./deploy/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deploy/favicon.svg:/usr/share/nginx/html/favicon.svg:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
